CREATE DATABASE IF NOT EXISTS task_api;

USE task_api;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL
);
